# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ff4041bde03620f6e88f852bda4c2bd81514118a5252cd0aed6b2cd846ba87db4722d8ad6bcc360d55970f373b400415b9bbe488b64fc0761a07b437bfad438

test:
  secret_key_base: 3a95c4045ee0e20d59aa03cd488399fc416be7d2f1b2dd8f882b718c0700e52177c272e651c7c8bdca95512c4d5bcd74b6be683e7f81061e3aa1a9c8c11fdff2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
